// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toolkxpkmkduvnwdbyqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvb2xreHBrbWtkdXZud2RieXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTExMzcsImV4cCI6MjA2OTI2NzEzN30.31RKh8LiL9EIUj1unax3347QnT5mW0QuXLXwtNs1w7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});